import { expect, test } from '@playwright/test'

test.describe.configure({ mode: 'serial' })

test('synthetic: durable live notification, duplicate delivery and read state survive refresh', async ({ page, request }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '合成測試專案', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^通知，/ }).click()
  const panel = page.getByRole('region', { name: '通知中心' })
  await expect(panel.getByText('通知連線正常')).toBeVisible()
  await expect(panel.locator('li')).toHaveCount(0)

  const first = await request.post('/__fixture__/completion', { data: { event_key: 'durable-completion' } })
  expect(first.ok()).toBeTruthy()
  const repeated = await request.post('/__fixture__/completion', { data: { event_key: 'durable-completion' } })
  expect((await repeated.json()).id).toBe((await first.json()).id)
  await expect(panel.locator('li')).toHaveCount(1)
  await expect(panel.getByText('Agent 已完成這一輪')).toBeVisible()
  await expect(page.getByRole('button', { name: '通知，1 則未讀', exact: true })).toBeVisible()

  await page.reload()
  await page.getByRole('button', { name: /^通知，/ }).click()
  await expect(panel.locator('li')).toHaveCount(1)
  await expect(panel.locator('li.is-unread')).toHaveCount(1)
  await panel.getByRole('button', { name: /Agent 已完成這一輪/ }).click()
  await expect(page.getByRole('button', { name: '通知，0 則未讀', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Agents', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /^通知，/ }).click()
  await expect(panel.locator('li')).toHaveCount(1)
  await expect(panel.locator('li.is-unread')).toHaveCount(0)
  await expect(page.locator('.notification-toast')).toHaveCount(0)
})

test('synthetic: default-denied runtime controls and real API remain safe on mobile', async ({ page, request }) => {
  const info = await (await request.get('/__fixture__/info')).json()
  expect(info.source).toBe('synthetic')
  const capability = await (await request.get('/api/capabilities')).json()
  expect(capability.allowed_actions).toEqual([])
  const denied = await request.post(`/api/projects/${info.project_id}/agents/start`, { data: { kind: 'codex' } })
  expect(denied.status()).toBe(403)
  expect((await denied.json()).code).toBe('action_not_authorized')

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('heading', { name: '合成測試專案', exact: true }).click()
  await page.getByRole('button', { name: 'Agents', exact: true }).click()
  await expect(page.getByRole('button', { name: '啟動 Agent', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '建立 Shell pane', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Send /model', exact: true })).toBeDisabled()
  await expect(page.getByText('合成測試：未連接任何真實 Herdr。')).toBeVisible()
  await page.getByRole('button', { name: /^通知，/ }).click()
  await expect(page.getByRole('region', { name: '通知中心' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('synthetic-mobile.png'), fullPage: true })
})

test('synthetic: UI submits acceptance to real API and shows verified work plus durable notification', async ({ page, request }) => {
  const info = await (await request.get('/__fixture__/info')).json()
  const policy = await request.put(`/api/projects/${info.project_id}/verification-policy/${info.node_id}`, {
    data: { required_gates: ['合成必要檢查'] },
  })
  expect(policy.status()).toBe(200)
  await page.goto('/')
  await page.getByRole('heading', { name: '合成測試專案', exact: true }).click()
  await page.getByRole('button', { name: '工作', exact: true }).click()
  const work = page.locator('.work-row').filter({ hasText: '合成成果：通知與驗收流程' })
  await expect(work.getByText('已實作・待驗證', { exact: true })).toBeVisible()
  await work.getByRole('button', { name: '查看已完成與待辦' }).click()
  await work.getByText('核對驗收證據', { exact: true }).click()
  const submit = work.getByRole('button', { name: '確認證據並保存驗收' })
  await expect(submit).toBeDisabled()
  await work.getByRole('checkbox', { name: `我已核對「${info.acceptance}」通過` }).check()
  await work.getByRole('checkbox', { name: '我已核對「合成必要檢查」通過' }).check()
  await work.getByLabel('驗收條件 1 的報告相對路徑（每行一項）').fill(info.evidence_path)
  await work.getByLabel('必要檢查 1 的報告相對路徑（每行一項）').fill(info.evidence_path)
  await expect(submit).toBeEnabled()
  const response = page.waitForResponse(res => res.url().endsWith(`/api/projects/${info.project_id}/verifications`) && res.request().method() === 'POST')
  await submit.click()
  expect((await response).status()).toBe(201)
  await expect(work.getByText('已有證據完成', { exact: true })).toBeVisible()
  await expect(work.getByText('1/1 個驗收條件已有證據', { exact: true })).toBeVisible()
  const project = await (await request.get(`/api/projects/${info.project_id}`)).json()
  expect(project.plan[0].state).toBe('verified')
  await page.getByRole('button', { name: /^通知，/ }).click()
  const panel = page.getByRole('region', { name: '通知中心' })
  await expect(panel.getByRole('button', { name: /項目已通過驗收/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /^通知，/ }).click()
  await expect(panel.getByRole('button', { name: /項目已通過驗收/ })).toBeVisible()
})
